// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/graph/expand/{id}": {
            "get": {
                "description": "Returns nodes and edges reachable from a node within N hops",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Expand a node N hops",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Traversal depth (default 2)",
                        "name": "hops",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/graph/politician/{id}": {
            "get": {
                "description": "Returns nodes and edges centered on a politician",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Politician-centric subgraph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Politician ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/graph/scandal/{id}": {
            "get": {
                "description": "Returns nodes and edges centered on a scandal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "graph"
                ],
                "summary": "Scandal-centric subgraph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scandal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/politician/{id}": {
            "get": {
                "description": "Returns full politician profile with all graph connections",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "politician"
                ],
                "summary": "Politician profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Politician ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PoliticianProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/politicians": {
            "get": {
                "description": "Paginated, filterable list of politicians. Gives a fresh install content to explore even before any scandals exist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "politician"
                ],
                "summary": "Browse politicians",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Case-insensitive name substring",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact party filter (party_current)",
                        "name": "party",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact state/UF filter (state)",
                        "name": "uf",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (1-based, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 24, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: connections (default, most linked first) or name",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PoliticianListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proceeding/{id}": {
            "get": {
                "description": "Returns one legal proceeding by node id, with the scandal it investigates and every defendant linked to it (including the DEFENDANT_IN edge's provenance).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proceeding"
                ],
                "summary": "Legal proceeding detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Legal proceeding node ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProceedingDetailResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proceedings": {
            "get": {
                "description": "Paginated list of legal proceedings. Walking every page enumerates the whole corpus, which is what the SEO sitemap does.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proceeding"
                ],
                "summary": "Browse legal proceedings",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 24, max 100)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ProceedingListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scandal/{id}": {
            "get": {
                "description": "Returns full scandal profile with all graph connections",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scandal"
                ],
                "summary": "Scandal profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Scandal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScandalProfileResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scandals": {
            "get": {
                "description": "Paginated list of scandals with involved-politician and linked-proceeding counts. Walking every page enumerates the whole corpus, which is what the SEO sitemap does.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scandal"
                ],
                "summary": "Browse scandals",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (1-based, default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 24, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: date (default, newest first) or name",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ScandalListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search across politicians, persons, scandals, organizations and sanctions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Full-text search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Node type filter: politician|person|scandal|organization|sanction",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/timeline": {
            "get": {
                "description": "Returns nodes and edges active within a date range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeline"
                ],
                "summary": "Timeline-filtered graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Edge": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.EdgeType"
                }
            }
        },
        "models.EdgeType": {
            "type": "string",
            "enum": [
                "INVOLVED_IN",
                "DEFENDANT_IN",
                "MEMBER_OF",
                "CONTROLS",
                "OWNED_BY",
                "IMPLICATED_IN",
                "INVESTIGATES",
                "RELATED_TO",
                "SUPPORTS",
                "SANCTIONED_IN"
            ],
            "x-enum-varnames": [
                "EdgeTypeInvolvedIn",
                "EdgeTypeDefendantIn",
                "EdgeTypeMemberOf",
                "EdgeTypeControls",
                "EdgeTypeOwnedBy",
                "EdgeTypeImplicatedIn",
                "EdgeTypeInvestigates",
                "EdgeTypeRelatedTo",
                "EdgeTypeSupports",
                "EdgeTypeSanctionedIn"
            ]
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.GraphResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Edge"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Node"
                    }
                }
            }
        },
        "models.Node": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "type": {
                    "$ref": "#/definitions/models.NodeType"
                }
            }
        },
        "models.NodeType": {
            "type": "string",
            "enum": [
                "politician",
                "person",
                "scandal",
                "organization",
                "legal_proceeding",
                "source",
                "sanction"
            ],
            "x-enum-varnames": [
                "NodeTypePolitician",
                "NodeTypePerson",
                "NodeTypeScandal",
                "NodeTypeOrganization",
                "NodeTypeLegalProceeding",
                "NodeTypeSource",
                "NodeTypeSanction"
            ]
        },
        "models.Politician": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "cpf": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "name_aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "party_current": {
                    "type": "string"
                },
                "photo_attribution": {
                    "type": "string"
                },
                "photo_source": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "role_current": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "tse_profile_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.PoliticianListItem": {
            "type": "object",
            "properties": {
                "connection_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "party_current": {
                    "type": "string"
                },
                "photo_attribution": {
                    "type": "string"
                },
                "photo_url": {
                    "type": "string"
                },
                "proceeding_count": {
                    "type": "integer"
                },
                "role_current": {
                    "type": "string"
                },
                "sanction_count": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "models.PoliticianListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PoliticianListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.PoliticianProfileResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "$ref": "#/definitions/models.GraphResponse"
                },
                "politician": {
                    "$ref": "#/definitions/models.Politician"
                }
            }
        },
        "models.ProceedingDefendant": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "confidence_signals": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outcome": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "source": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.ProceedingDetailResponse": {
            "type": "object",
            "properties": {
                "assuntos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "case_number": {
                    "type": "string"
                },
                "court": {
                    "type": "string"
                },
                "defendants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProceedingDefendant"
                    }
                },
                "has_conviction": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "scandal": {
                    "$ref": "#/definitions/models.ProceedingScandalRef"
                },
                "status": {
                    "$ref": "#/definitions/models.ProceedingStatus"
                },
                "type": {
                    "$ref": "#/definitions/models.ProceedingType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.ProceedingListItem": {
            "type": "object",
            "properties": {
                "case_number": {
                    "type": "string"
                },
                "court": {
                    "type": "string"
                },
                "has_conviction": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.ProceedingStatus"
                },
                "type": {
                    "$ref": "#/definitions/models.ProceedingType"
                }
            }
        },
        "models.ProceedingListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProceedingListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.ProceedingScandalRef": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ProceedingStatus": {
            "type": "string",
            "enum": [
                "ongoing",
                "concluded"
            ],
            "x-enum-varnames": [
                "ProceedingStatusOngoing",
                "ProceedingStatusConcluded"
            ]
        },
        "models.ProceedingType": {
            "type": "string",
            "enum": [
                "criminal",
                "administrative",
                "cpi"
            ],
            "x-enum-varnames": [
                "ProceedingTypeCriminal",
                "ProceedingTypeAdministrative",
                "ProceedingTypeCPI"
            ]
        },
        "models.Scandal": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "date_end": {
                    "type": "string"
                },
                "date_start": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "ongoing|concluded|prescribed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.StatusType"
                        }
                    ]
                },
                "total_amount_brl": {
                    "type": "number"
                },
                "wikipedia_url": {
                    "type": "string"
                }
            }
        },
        "models.ScandalListItem": {
            "type": "object",
            "properties": {
                "date_end": {
                    "type": "string"
                },
                "date_start": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "politician_count": {
                    "type": "integer"
                },
                "proceeding_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/models.StatusType"
                }
            }
        },
        "models.ScandalListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ScandalListItem"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.ScandalProfileResponse": {
            "type": "object",
            "properties": {
                "connections": {
                    "$ref": "#/definitions/models.GraphResponse"
                },
                "scandal": {
                    "$ref": "#/definitions/models.Scandal"
                }
            }
        },
        "models.StatusType": {
            "type": "string",
            "enum": [
                "ongoing",
                "concluded",
                "prescribed"
            ],
            "x-enum-varnames": [
                "StatusTypeOngoing",
                "StatusTypeConcluded",
                "StatusTypePrescribed"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "⌬ API",
	Description:      "Corruption graph api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
